language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
# install dependencies from setup.py
   - pip install .
# install dependencies from requirements.txt
#   - pip install -r requirements.txt
# run nose tests
script: nosetests
